on: push
name: Lint

jobs:
  rustfmt:
    name: Run rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt
      - run: cargo fmt --check
      - run: cargo clippy --no-deps --workspace --all-targets
  clippy-and-test:
    name: Other build/test
    strategy:
      fail-fast: false
      matrix:
        rust_version: [ nightly ]
        os:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust_version }}
          components: clippy


      # Don't run clippy on Windows, we only need to run it on Linux
      - if: runner.os != 'windows'
        run: cargo clippy --no-deps --workspace --all-targets

      - run: cargo test --workspace
